### ISSUE TITLE
Cash2 calculation wrong. 

### ISSUE THREAD

**Issue by 3ricj** [KizmoTek/Mining-Calculator#2]
Antminer a3 really only gets effectively 350gh because of cash2 block times.   Per them: 

"Hello,

This is normal. It is due to Cash2's fast block times. The miner has to constantly switch to mining a new block every 9 seconds, and this causes an increase in discarded shares. Also, it takes time for the new block information to be sent from the pool server to you miner. This delay also prevents the miner from hashing at its full potential. All of this combined causes the pool's recorded hashrate from your miner to be less than what your miner is actually capable of.

Paul"

**Comment by KizmoTek** [comment]
Hi, I cant accurately divide the result to make it show the proper profit, however if you input the hashrate that shows up on your pool, the profit should be pretty accurate. 
I do have a tooltip right next to the Cash2 coin name that tells you to input the hashrate that shows up on the pool. Right now I cant do anything else about it unless if Cash2 optimizes pool code so that the hashrate is always stable at a set amount and then I would be able to divided to show the correct results.

-Gaming Radar101
![image](https://user-images.githubusercontent.com/14062618/55433479-53009a00-554a-11e9-85a0-836199055949.png)

**Comment by MasterHW** [comment]
perhaps we should add a slider for "Miner Spec." vs "Actual" for CASH2.

**Comment by KizmoTek** [comment]
Code was updated some time ago, the preset hashrate calculation is lowered for Cash2 to provide a bit more of an accurate result. Custom hashrate inputs are not lowered for Cash2 because some people might want to put the exact hashrate they get on a Cash2 pool.
